### ISSUE TITLE
Wrong highlighting with underscore

### ISSUE THREAD

**Issue by stefanocoretta** [Kerrigan29a/language-literate#3]
Not sure if it is a bug or if I can just change some settings, but when I use the underscore _, everything after it is in italics and purple.

![screen shot 2016-07-04 at 10 45 06](https://cloud.githubusercontent.com/assets/6429302/16556873/669c02d4-41d4-11e6-8249-3e0874d452e4.png)

**Comment by Kerrigan29a** [comment]
It seems the problem appears when using the GMF version. If you change `<!--- literate: syntax=markdown -->` to `<!--- literate: -->` (And trigger autodetect syntax again) it disappears. Also you can force the syntax to "Literate code" instead of "Literate code (Markdown)"

If you look at [literate-gmf code](https://github.com/Kerrigan29a/language-literate/blob/master/grammars/gfm_literate.cson) you can see that I'm just mixing both grammars, so this behaviour is due to GMF syntax.

Maybe you can change `"_no"` to ``_no`` as you are talking about code.

Thanks for your issue

**Comment by stefanocoretta** [comment]
I switched to Literate code and that solved the problem (I don't know why I was using the other option since the idea was to write in LaTeX, not in MarkDown).

Thanks!
